
package principal.frontend.gui.calendari_cholquij.matriz;

import principal.backend.calendari_cholquij.matriz.manejadorCalendarioExpandido;



/**
 *
 * @author richard
 */
public class matrizCholquijFrame extends javax.swing.JFrame {

    manejadorCalendarioExpandido manejador;

    public matrizCholquijFrame() {
        initComponents();
        manejador = new manejadorCalendarioExpandido();
        manejador.cuadricula(cuadroPanel, infoTextArea,labelNahual,labelEnergia);
        manejador.cargarDatos();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuadroPanel = new javax.swing.JPanel();
        panelEnergia = new javax.swing.JPanel();
        labelEnergia = new javax.swing.JLabel();
        panelNahual = new javax.swing.JPanel();
        labelNahual = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1050, 500));
        setResizable(false);

        cuadroPanel.setFont(new java.awt.Font("Waree", 0, 14)); // NOI18N

        javax.swing.GroupLayout cuadroPanelLayout = new javax.swing.GroupLayout(cuadroPanel);
        cuadroPanel.setLayout(cuadroPanelLayout);
        cuadroPanelLayout.setHorizontalGroup(
            cuadroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        cuadroPanelLayout.setVerticalGroup(
            cuadroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelEnergia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENERGIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Waree", 1, 14))); // NOI18N

        javax.swing.GroupLayout panelEnergiaLayout = new javax.swing.GroupLayout(panelEnergia);
        panelEnergia.setLayout(panelEnergiaLayout);
        panelEnergiaLayout.setHorizontalGroup(
            panelEnergiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnergiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEnergia, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEnergiaLayout.setVerticalGroup(
            panelEnergiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnergiaLayout.createSequentialGroup()
                .addComponent(labelEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelNahual.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NAHUAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Waree", 1, 14))); // NOI18N

        javax.swing.GroupLayout panelNahualLayout = new javax.swing.GroupLayout(panelNahual);
        panelNahual.setLayout(panelNahualLayout);
        panelNahualLayout.setHorizontalGroup(
            panelNahualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNahualLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNahual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNahualLayout.setVerticalGroup(
            panelNahualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNahualLayout.createSequentialGroup()
                .addComponent(labelNahual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        infoTextArea.setEditable(false);
        infoTextArea.setBackground(new java.awt.Color(204, 204, 204));
        infoTextArea.setColumns(20);
        infoTextArea.setFont(new java.awt.Font("URW Gothic", 0, 14)); // NOI18N
        infoTextArea.setLineWrap(true);
        infoTextArea.setRows(5);
        infoTextArea.setWrapStyleWord(true);
        infoTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Waree", 1, 14))); // NOI18N
        jScrollPane2.setViewportView(infoTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cuadroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelNahual, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelNahual, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addComponent(cuadroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cuadroPanel;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelEnergia;
    private javax.swing.JLabel labelNahual;
    private javax.swing.JPanel panelEnergia;
    private javax.swing.JPanel panelNahual;
    // End of variables declaration//GEN-END:variables
}
